name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create simple site
        run: |
          mkdir -p public
          echo "<h1>Logseq Notlarım</h1>" > public/index.html
          echo "<p>Site yakında hazır olacak!</p>" >> public/index.html
          cp hoşgeldin.md public/
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
